name: C/C++ CI Fedora Latest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: fedora-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make check
      run: make check
