name: C/C++ CI Ubuntu Latest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: make check
      run: make check
